# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "CentOS-6.4-x86_64"
  config.vm.box_download_insecure = true
  config.vm.box_url = "https://acrws-jenkins.geocent.com/vagrant/CentOS-6.4-x86_64-v2.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # ansible is not supported on windows, so we bootstrap it in VM and run the playbooks
  require 'rbconfig'
  is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)
  if is_windows
    config.vm.provision "shell" do |sh|
      sh.path = "scripts/windows.sh"
      sh.args = "site.yml hosts"
    end
  else
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  config.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
end
